
export default {
// COLORS
  COLOR_BLUE: '#3f8eff',
  COLOR_BLUE_LIGHT: '#33ccff',
  COLOR_ORANGE: '#ffae00',
  COLOR_RED: '#ff3c00',
  COLOR_RED_DARK: '#d75a4a',
  COLOR_BLACK: '#000124',
  COLOR_WHITE: '#ffffff',
  COLOR_GRAY_HEAVY: '#515151',
  COLOR_GRAY_MEDIUM: '#999999',
  COLOR_GRAY_LIGHT: '#cccaca',
  COLOR_NOTIFICATION: '#000000',
  COLOR_PAGE: '#fafafa',
  COLOR_PAGE_HIGHLIGHT: '#f0f0f0',

// FONTS
  FONT_SIZE_SMALL: 12,
  FONT_SIZE_MEDIUM: 25,
  FONT_SIZE_LARGE: 35,

// CONTAINERS
  CONTAINER_PADDING: 20
};
