export WelcomeLabel from './WelcomeLabel';
export WelcomeAdditional from './WelcomeAdditional';
export WelcomeCommon from './WelcomeCommon';
export CommonText from './CommonText';
export LabelText from './LabelText';
export NavCommonText from './NavCommonText';
export NavLabelText from './NavLabelText';
export OtherTextButton from './OtherTextButton';
export WelcomeTextButton from './WelcomeTextButton';
