// AUTHENTICATION TYPES
export const AUTH = {
  SIGNUP: {
    REQUEST: 'AUTH_SIGNUP_REQUEST',
    SUCCESS: 'AUTH_SIGNUP_SUCCESS',
    FAILED: 'AUTH_SIGNUP_FAILED',
  },
  LOGIN: {
    REQUEST: 'AUTH_LOGIN_REQUEST',
    SUCCESS: 'AUTH_LOGIN_SUCCESS',
    FAILED: 'AUTH_LOGIN_FAILED',
  },
  LINK: {
    REQUEST: 'AUTH_LINK_REQUEST',
    SUCCESS: 'AUTH_LINK_SUCCESS',
    FAILED: 'AUTH_LINK_FAILED',
  },
  LOGOUT: 'AUTH_LOGOUT'
};

export const USER = {
  GET: {
    PROFILE: {
      REQUEST: 'USER_GET_PROFILE_REQUEST',
      SUCCESS: 'USER_GET_PROFILE_SUCCESS',
      FAILED: 'USER_GET_PROFILE_FAILED',
    },
    TOKEN: 'USER_GET_TOKEN',
  },
};

export const NOTIFICATION = {
  GET: {
      REQUEST: 'NOTIFICATION_GET_REQUEST',
      SUCCESS: 'NOTIFICATION_GET_SUCCESS',
      FAILED: 'NOTIFICATION_GET_FAILED',
  },
};

export const CAMPAIGN = {
  SELECTED: 'CAMPAIGN_SELECTED',
  BROWSE: {
    REQUEST: 'CAMPAIGN_BROWSE_REQUEST',
    SUCCESS: 'CAMPAIGN_BROWSE_SUCCESS',
    FAILED: 'CAMPAIGN_BROWSE_FAILED',
  },
  MYLIST: {
    REQUEST: 'CAMPAIGN_MYLIST_REQUEST',
    SUCCESS: 'CAMPAIGN_MYLIST_SUCCESS',
    FAILED: 'CAMPAIGN_MYLIST_FAILED',
  }
 
};
 